var inp = {
  LoginScreen: {
    PHONE: "Telefon",
    LOGIN: "Login",
    REGISTER: "Register",
    EMAIL: "Email",
    PASSWORD: "password",
    NAME: "Full Name",
    INVITECODE: "Invite code",
    LOGIN_BTN: "Login",
    CANCEL: "Cancel",
    FORGOT_PASSWORD: "Forgot Password",
    CONFIRM_PASSWORD: "Confirm Password",
    LOGIN_USING_SOCIAL: "Login using Social Media",
    REMEMBER_ME: "Remember Me",
    EMAIL_REQUIRED: "Email is Mandatory 1",
    PASSWORD_REQUIRED: "Password is Mandatory",
    CONFIRM_PASSWORD_REQUIRED: "Confirm Password is Mandatory",
    EMAIL_LEN_VALID: "Username should be atleast",
    EMAIL_VALID: "Email Should be valid",
    PASSWORD_CONFIRM_VALID: "Password and Confirm Password should be same",
    EMAIL_OR_PASSWORD_INVALID: "Email Or Password is Invalid",
    I_AGREE_TO_TERMS_AND_CONDITION: "I Agree to terms and Condition",
    ERROR_OCCURRED: "Error Occurred. Please contact the admin",
    IAGREE: "I agree to",
    TERMS: " terms and conditions",
    MUST_AGREE: "You must agree to terms and conditions",
    NAME_REQUIRED: "Full Name is mandatory",
    LOGIN_USING: "Zaloguj się",
    LOGIN_USING_EMAILID: "Login Using Email ID",
    INVITECODE_HINT:
      "Please enter the invite code before clicking the social icons",
    OR: "Or",
    MUST_AGREE_VALID: "You must agree to terms and conditions",
    PASSWORD_LEN_VALID: "Password length should be greater than 6",
    INVALID_USER: "Invalid User",
    CHANGE_PASSWORD: "Change Password",
    LOGIN_SUCCESS: " Login success",
    CREATED_ACCOUNT_SUCCESSFULLY:
      "Created account successfully. Please check email for password",
    INVALID_EMAIL: "Invalid email address",
    PASSWORD_RESET_SUCCESS: "PASSWORD changed successfully",
    GOBACK: "Go back",
    RULES_TITLE: "Regulamin",
    ACCEPT_BTN: "Accept"
  },
  RulesScreen: {
    TITLE: "Company Rules",
    ACCEPT_BTN: "Accept"
  },
  RewardsScreen: {
    POINTS: "Points",
    BUY_BTN: "Buy",
    BUY: "Buy",
    SAVED_ADDRESS: "Saved Address",
    NEW_ADDRESS: " New Address",
    ZIPCODE: "Zip Code",
    COUNTRY: "Country",
    CITY: "City",
    ADDRESS: "Address",
    NAME: "Name",
    NAME_REQUIRED: "Name is mandatory",
    ZIPCODE_REQUIRED: "Zipcode is mandatory",
    APARTMENTNO: "Apartment No",
    STREETNO: "Street No",
    PURCHASE_BTN: "Purchase",
    GOTO_HOME: "Go to Home",
    PURCHASE_SUCCESSFUL: "Successfully Purchased"
  },
  AppScreen: {
    WELCOME: "Welcome to Loyalty App",
    APP_TITLE: "Loyalty App",
    POINTS: "Points",
    REWARD_TITLE: "Twoje promocje",
    NO_REWARDS_PLACEHOLDER: "Brak aktywowanych promocji. Dodaj je na stronie internetowej.",
    CASHBACK_TITLE: "Cashback",
    YOUR_SCORES: "Your Total Reward",
    HISTORY: "Your history",
    TASKS_TITLE: "Tasks",
    PRICE: "Price",
    NO_HISTORY_FOUND: "No History Found",
    SURVEY_ANSWERED: "Survey answered",
    SURVEY_VIEWED: "Survey viewed",
    BARCODE_SCANNED: "Barcode scanned",
    REGISTRATION_WITH_INVITE_CODE: "Registration with invitation code",
    BOUGHT_A_PRICE: "Bought A Price",
    BALANCE: "Balance",
    CONTENT_TITLE: "Cashback",
    RANKING: "Ranking"
  },
  TaskScreen: {
    FILL_SURVEY: "Fill up the Survey",
    SCAN_QR: "Scan QR Code",
    INVITE_FRIEND: "Invite Friends",
    WHAT_YOU_GET: "What you can get",
    TASKS: "Tasks",
    HISTORY: "History",
    START: "Start",
    SCAN: "Scan",
    INVITE: "Invite",
    SUBMIT: "Submit",
    GOTO_HOME: "Go to Home",
    THANK_YOU: "Thank You",
    SURVEY_POINTS_YOU_GET:
      "You can get {point} points for filling up the survey",
    SURVEY_POINTS_YOU_GOT:
      "You have got {point} points for filling up the survey",
    FILL_UP_SURVEY: "You can fill up the survey just one time ",
    ALREADY_FILLED_SURVEY: "You have already filled up the survey",
    INVITE_USER: "You will receive {point} points for each person you invite ",
    USER_REGISTERED:
      "User registered with your recommendation will get {point} points",
    SCAN_QRCODE: "You can get {point} points for scaning QR ",
    YOUR_INVITE_CODE: "Your Invite Code",
    COPY_INVITE_CODE: "Click to copy Invite Code",
    INVITE_CODE_COPIED: "Invite Code Copied",
    CLICK_TO_SCAN_QRCODE: "Click Scan button and place your camera to QR code ",
    USER_REGISTERED_WITH_CODE: "User {user} registered with your link",
    QR_SCANNED: "QR Code Scanned",
    SURVEY_FILLED: "Survey filled",
    CAMERA_ACCESS_NOT_ALLOWED: "Camera access permission is not granted",
    NO_CAMERA_FOUND: "No Camera found",
    CAMERA_COMMON_ISSUE: "Camera issue, please contact admin",
    INVALID_TASK: "Invalid Task",
    NO_QUESTIONS: "No Questions",
    BAR_CODE_SCANNED_SUCCESSFULLY: "Bar code scanned succesfully",
    NO_INVITE_CODE: "No invite code found",
    LOGIN_OPTION_PHONE: "SMS",
    LOGIN_OPTION_FACE: "Face ID"
  },
  Cashback: {
    REQUEST_SUCCESSFULL: "Data saved successfully"
  },
  Errors: {
    FAILED_TO_LOAD: "Failed to Load the App. Please contact the administrator",
    FAILED_TO_LOAD_COMPANY_ISSUE:
      "Failed to Load the App since company missing or invalid company. Please contact the administrator ",
    UNABLE_TO_CREATE_ACCOUNT: "Invalid Email",
    ACCOUNT_ALREADY_EXISTS: "Email Already Registered",
    NO_COMPANY_FOUND: "invalid URL is used to register",
    COMPANY_URL_IS_REQUIRED: "email, company_url, name is empty",
    EMAIL_IS_REQUIRED: "email value passed as empty",
    NAME_IS_REQUIRED: "email, company_url, name is empty",
    LOGIN_FAILED: "Invalid Username or Password",
    INCORRECT_EMAIL_FORMAT: "Incorrect Email format",
    INCORRECT_EMAIL_OR_PASSWORD: "Invalid email or password",
    PASSWORD_IS_REQUIRED: "Password is required",
    FBLOGIN_ERROR: "Error Occcurred in face book login",
    GOOGLELOGIN_ERROR: "Error Occcurred in google login",
    INVALID_ACCESS_TOKEN: "Invalid access token",
    ACCESS_TOKEN_IS_REQUIRED: "Access token is invalid",
    ACCOUNT_NOT_FOUND: "invalid Email is provided",
    FAILED_TO_PURCHASE: "Purchase request failed",
    PRODUCT_ID_IS_REQUIRED: "Product is required",
    INSUFFICIENT_POINT: "Insufficient Points",
    PRODUCT_DOES_NOT_BELONG_TO_THIS_COMPANY: "Product is not valid",
    NO_PRODUCT_FOUND: "Invalid Product",
    PURCHASE_LIMIT_EXCEEDED: "Purchase Limit Exceeded",
    USER_DONT_BELONG_TO_THIS_COMPANY: "User is invalid to buy product",
    ERROR_OCCURRED_BARCODE_SCAN: "Error occurred in barcode scan",
    YOU_HAVE_SCANNED_THIS_BARCODE_ALREADY: "Barcode scanned already",
    BARCODE_ALREADY_USED: "Barcode already used",
    INVALID_DATA_SUBMITTED: "Invalid form data submitted",
    INVALID_QUESTION_ID: "Invalid Question ID",
    CASHBACK_ERROR_SUBMIT: "Niepoprawne dane",
    CASHBACK_WRONG_BANK_ACCOUNT: "Niepoprawne znaczenie pola dla: Konto bankowe",
    CASHBACK_WRONG_NAME: "Niepoprawne znaczenie pola dla: Imię",
    CASHBACK_WRONG_SUMM: "Niepoprawne znaczenie pola dla: Ilość",
    INVALID_PHONE: "Błędny numer telefonu",
    USER_NOT_FOUND: "User not found"
  }
};
